# Generated by Django 4.1.7 on 2023-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
